-- <------ print number of books in DB ------>
SELECT 
    COUNT(*) AS 'Number of books'
FROM
    books;

-- <------ PRINTS BOOKS RELEASED IN EACH YEAR ------>
SELECT 
    RELEASED_YEAR AS YEAR, COUNT(*)
FROM
    BOOKS
GROUP BY RELEASED_YEAR
ORDER BY YEAR;

-- <------ SUM OF BOOKS IN STOCK ------>
SELECT 
    SUM(STOCK_QUANTITY)
FROM
    BOOKS;

-- <----- AVG RELEASED YEAR FOR EACH AUTHOR ---->
SELECT 
    CONCAT_WS(' ', AUTHOR_FNAME, AUTHOR_LNAME) AS AUTHOR,
    AVG(RELEASED_YEAR)
FROM
    BOOKS
GROUP BY AUTHOR;

-- <----- FULL NAME OF AUTHOR WITH LONGEST BOOK ---->

SELECT 
    CONCAT_WS(' ', AUTHOR_FNAME, AUTHOR_LNAME) AS AUTHOR
FROM
    BOOKS
WHERE
    PAGES = (SELECT 
            MAX(PAGES)
        FROM
            BOOKS);

-- <-------- FINAL EXERCISE ------>

SELECT 
    RELEASED_YEAR AS YEAR,
    COUNT(*) AS BOOKS,
    AVG(PAGES) AS 'AVG PAGES'
FROM
    BOOKS
GROUP BY YEAR
ORDER BY YEAR; 