use book_shop;

-- GROUP BY
SELECT author_lname,count(*) FROM books GROUP BY author_lname;
SELECT author_lname,count(*) AS books_written FROM books GROUP BY author_lname ORDER BY books_written  DESC; 
SELECT released_year,count(*) AS books_released  FROM books;
select released_year,count(*) from books group by released_year order by released_year;

-- MIN AND MAX

SELECT MIN(RELEASED_YEAR) FROM BOOKS;
SELECT MIN(PAGES) FROM BOOKS;

  -- SUB QUERIES
SELECT * FROM BOOKS WHERE PAGES = (SELECT MIN(PAGES) FROM BOOKS);  
SELECT * FROM BOOKS WHERE STOCK_QUANTITY=(SELECT MAX(STOCK_QUANTITY) FROM BOOKS);
SELECT TITLE,RELEASED_YEAR FROM BOOKS WHERE RELEASED_YEAR=(SELECT MIN(RELEASED_YEAR) FROM BOOKS);

-- GROUPING BY MULTIPLE COLUMNS

SELECT AUTHOR_FNAME,AUTHOR_LNAME,COUNT(*) FROM BOOKS GROUP BY AUTHOR_LNAME,AUTHOR_FNAME;
SELECT CONCAT_WS(' ',AUTHOR_FNAME,AUTHOR_LNAME) AS AUTHOR,COUNT(*) FROM BOOKS GROUP BY AUTHOR;

-- MIN AND MAX WITH GROUPING
     -- selecting min and max published for an author
SELECT CONCAT_WS(' ',AUTHOR_FNAME,AUTHOR_LNAME) AS AUTHOR,MIN(RELEASED_YEAR) AS FIRST_BOOK,MAX(RELEASED_YEAR) AS LAST_BOOK FROM BOOKS GROUP BY AUTHOR;

-- SUM
SELECT SUM(PAGES) FROM BOOKS;
SELECT CONCAT_WS(' ',AUTHOR_LNAME,AUTHOR_FNAME) AS AUTHOR,SUM(PAGES) FROM BOOKS GROUP BY AUTHOR;

-- AVG
SELECT AVG(RELEASED_YEAR) FROM BOOKS;
SELECT AVG(PAGES) FROM BOOKS;
SELECT CONCAT_WS(' ',AUTHOR_FNAME,AUTHOR_LNAME) AS AUTHOR,AVG(PAGES) AS AVERAGE_PAGE_WRITTEN FROM BOOKS GROUP BY AUTHOR;
SELECT RELEASED_YEAR,AVG(STOCK_QUANTITY),COUNT(*) FROM BOOKS GROUP BY RELEASED_YEAR ORDER BY RELEASED_YEAR DESC;

